title: Qubit Noise Spectroscopy
email: fertmeneses@gmail.com
logo: assets/QNS_logo.png
description: A Machine Learning approach for imaging magnetic noise, by Fernando Meneses.
show_downloads: True
theme: jekyll-theme-minimal
